version: "3.9"

services:
    database:
        image: woahbase/alpine-mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PWD: "@1234"
            MYSQL_USER_DB: "dev"
            MYSQL_USER: "dev_usr"
            MYSQL_USER_PWD: "dev_pwd"
